### PR TITLE
fix: change the development check

### PR DESCRIPTION
**Pull request by nethunter**
In the latest nuxt, config.dev is not set, I think you should check config.mode === 'development'

### CODE REVIEW

**Comment by nethunter** [comment]
@daliborgogic I also think that you've removed all the configurations from this version :)

**Comment by daliborgogic** [comment]
@nethunter don't tell anyone, didn't paste the rest. For `mode` property possibe values are: `spa` for no-server-side rendering and `universal` for isomporphic application. Information about running environment is  `dev` [#L12](https://github.com/nuxt/nuxt.js/blob/2.x/lib/common/nuxt.config.js#L12)

edit: typo

**Comment by daliborgogic** [comment]
Set `if (config.dev) return`, then we can make merge pull request. Thank you!

**Comment by daliborgogic** [comment]
Much better approach:
```javascript
this.extendBuild((config,  { isDev }) => {
   if (isDev) return
   ...
})
```
More info: https://nuxtjs.org/faq/extend-webpack#how-to-extend-webpack-config-

**Comment by nethunter** [comment]
@daliborgogic yeah, that makes sense, is much cleaner. Pushed it now.

**Pull request merged**
